name = "Pricenometry"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "Theme for a static version of Pricenometry.com"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.21

[author]
    name = "Michael Bastos"
    homepage = "https://michaelbastos.com"
